/**
 * Dataverse Demo App - Main Application Component
 *
 * This app demonstrates how to use Power Apps code apps with Dataverse:
 * - CRUD operations (Create, Read, Update, Delete) on Contact and Account entities
 * - Lookup fields (linking Contacts to Accounts)
 * - Query-parameter routing between Dataverse tables
 * - Error handling and best practices
 * - Component-based architecture
 *
 * ARCHITECTURE PATTERN:
 * ====================
 * The app follows a clean three-layer architecture:
 *
 * 1. COMPONENTS (Presentation Layer):
 *    - Pure presentational components (UI only, no business logic)
 *    - Receive data via props, emit events via callbacks
 *    - Examples: Header, ContactList, ContactForm, AccountList, AccountForm,
 *                SystemUserList, ErrorMessage
 *
 * 2. HOOKS (Business Logic Layer):
 *    - Custom hooks that manage state and orchestrate services
 *    - Handle error handling, loading states, and data transformations
 *    - Examples: useContacts, useAccounts, useAccountsCrud, useLookupResolver
 *
 * 3. SERVICES (Data Access Layer):
 *    - Auto-generated by Power Apps CLI from Dataverse metadata
 *    - Handle all API communication with Dataverse
 *    - Examples: ContactsService, AccountsService, SystemusersService
 *
 * DATA FLOW:
 * ==========
 * User Action → Component → Hook → Service → Dataverse
 * Dataverse → Service → Hook → Component → UI Update
 *
 * This separation ensures:
 * - Testability: Each layer can be tested independently
 * - Maintainability: Changes to one layer don't cascade to others
 * - Reusability: Hooks and components can be reused across the app
 * - Clarity: Clear boundaries between presentation, logic, and data access
 */

import {
  Header,
  ErrorMessage,
  ContactList,
  ContactForm,
  AccountList,
  AccountForm,
  SystemUserList,
} from './components';
import {
  type ActivePage,
  useAccounts,
  useAccountsCrud,
  useContacts,
  useContextPage,
  useSystemUsers,
} from './hooks';
import './App.css';

function App() {
  const { activePage, setActivePage, contextError } = useContextPage();

  // PATTERN: Custom hooks handle all the business logic and state management
  // The component stays simple and focused on rendering UI
  const {
    contacts,
    loading: contactsLoading,
    error: contactsError,
    selectedContact,
    isCreating: isCreatingContact,
    startCreate: startCreateContact,
    selectContact,
    cancelForm: cancelContactForm,
    handleFormSubmit: handleContactFormSubmit,
    deleteContact,
  } = useContacts();

  // Load accounts for the Managing Partner lookup dropdown in the Contact form
  const { accounts } = useAccounts();

  // Full CRUD hook for the Accounts page
  const {
    accounts: accountsList,
    loading: accountsLoading,
    error: accountsError,
    selectedAccount,
    isCreating: isCreatingAccount,
    startCreate: startCreateAccount,
    selectAccount,
    cancelForm: cancelAccountForm,
    handleFormSubmit: handleAccountFormSubmit,
    deleteAccount,
  } = useAccountsCrud();

  const {
    systemUsers,
    loading: systemUsersLoading,
    error: systemUsersError,
  } = useSystemUsers();

  return (
    <div className="app-container">
      {/* Header Section */}
      <Header
        title="Dataverse Table Explorer"
        description="Uses the table query parameter from the app link to select the initial Dataverse table"
      />

      <ErrorMessage error={contextError} />

      <div className="table-selector">
        <label htmlFor="table-select">Dataverse table</label>
        <select
          id="table-select"
          value={activePage}
          onChange={(event) => setActivePage(event.target.value as ActivePage)}
        >
          <option value="contacts">Contacts</option>
          <option value="accounts">Accounts</option>
          <option value="systemusers">System Users</option>
        </select>
      </div>

      {activePage === 'contacts' && (
        <>
          <ErrorMessage error={contactsError} />
          <div className="content-grid">
            <ContactList
              contacts={contacts}
              selectedContact={selectedContact}
              loading={contactsLoading}
              onSelect={selectContact}
              onCreateNew={startCreateContact}
            />
            {(isCreatingContact || selectedContact) && (
              <ContactForm
                key={
                  isCreatingContact
                    ? 'new-contact'
                    : (selectedContact?.contactid ?? 'selected-contact')
                }
                selectedContact={selectedContact}
                isCreating={isCreatingContact}
                accounts={accounts}
                onSubmit={handleContactFormSubmit}
                onCancel={cancelContactForm}
                onDelete={deleteContact}
              />
            )}
          </div>
        </>
      )}

      {activePage === 'accounts' && (
        <>
          <ErrorMessage error={accountsError} />
          <div className="content-grid">
            <AccountList
              accounts={accountsList}
              selectedAccount={selectedAccount}
              loading={accountsLoading}
              onSelect={selectAccount}
              onCreateNew={startCreateAccount}
            />
            {(isCreatingAccount || selectedAccount) && (
              <AccountForm
                key={
                  isCreatingAccount
                    ? 'new-account'
                    : (selectedAccount?.accountid ?? 'selected-account')
                }
                selectedAccount={selectedAccount}
                isCreating={isCreatingAccount}
                onSubmit={handleAccountFormSubmit}
                onCancel={cancelAccountForm}
                onDelete={deleteAccount}
              />
            )}
          </div>
        </>
      )}

      {activePage === 'systemusers' && (
        <>
          <ErrorMessage error={systemUsersError} />
          <SystemUserList systemUsers={systemUsers} loading={systemUsersLoading} />
        </>
      )}
    </div>
  );
}

export default App;
